### ISSUE TITLE
Roadmap: v3

### ISSUE THREAD

**Issue by ankitpokhrel** [ankitpokhrel/tus-php#321]
> This is a living document and is subjected to change.

Q | A
-- | --
Status | DRAFT
Type | Feature
BC Break | Yes
Min PHP Version | 8.0 (?)
Dev Branch | [v3](https://github.com/ankitpokhrel/tus-php/tree/v3)
Release Date | N/A
Release Version | 3.0.0

#### Possible Changes

- [ ] Full PHP8 support
- [ ] [PSR-6](https://www.php-fig.org/psr/psr-6/)/[PSR-16](https://www.php-fig.org/psr/psr-16/) compatible cache implementation (see #287)
- [ ] Switch to [PSR12](https://www.php-fig.org/psr/psr-12/) (see #189)
- [ ] Move to GitHub actions (?)

**Comment by samundra** [comment]
>  All PRs must be targeted to v3 branch.

Should we instead target new PRs only to `v3` branch?

**Comment by ankitpokhrel** [comment]
> Should we instead target new PRs only to v3 branch?

I would say:

**v2**
- Fixes and features that can be ported easily to v3.
- But, all new changes must be compatible with PHP8.

**v3**
- Incompatible and major changes.
- Port changes that are applied in v2 to v3 regularly.

If v2 and v3 branches diverge by a lot, then we can stop accepting features in v2. But I don't think it is necessary at this phase.

**Comment by samundra** [comment]
Sounds good.
